### ISSUE TITLE
Getting exception on herokuAppDeploy

### ISSUE THREAD

**Issue by kmccarp** [marc0der/gradle-heroku#2]
I've successfully created the app in heroku (thanks to your gradle plugin!), now I'm trying to deploy it, and I get the following:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':herokuAppDeploy'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:72)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:49)
    at (omitting because, holy crap there are too many)
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of push command
    at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:178)
    at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:79)
    at java_util_concurrent_Callable$call.call(Unknown Source)
    at com.wiredforcode.HerokuAppDeployTask.execute(HerokuAppDeployTask.groovy:25)
    at com.wiredforcode.HerokuAppDeployTask$execute.callCurrent(Unknown Source)
    at com.wiredforcode.HerokuTask.start(HerokuTask.groovy:25)
    at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:216)
    at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:122)
    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
    at com.wiredforcode.HerokuAppDeployTask_Decorated.invokeMethod(Unknown Source)
    at org.gradle.util.ReflectionUtil.invoke(ReflectionUtil.groovy:23)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$4.execute(AnnotationProcessingTaskFactory.java:161)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$4.execute(AnnotationProcessingTaskFactory.java:156)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:510)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:499)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:64)
    ... 80 more
Caused by: java.io.IOException: Source ref master doesnt resolve to any object.
    at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:288)
    at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:192)
    at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:641)
    at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:1242)
    at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:152)
    ... 95 more
```

**Comment by kmccarp** [comment]
I've issued [a pull request](https://github.com/marcoVermeulen/gradle-heroku/pull/3) for this.

**Comment by marc0der** [comment]
I'd like to replicate this locally first. Could please let me know what your exact workflow is? I've tried replicating this in a brand new app and don't see you exceptions.

My workflow was as follows:

```
gradle herokuAppCreate #creates the git repo locally, master tracking remote
#start developing
git add path/to/file
git commit -m 'Some message'
gradle herokuAppDeploy
```
